#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMAs2KT3KXvm/Uj1y28Yo0csVCOY+HIIDg3d04UK+OSp anton@ubuntuteach
