[all:vars]
ansible_user=ubuntu

[bastion]
bastion ansible_host=bastion

[web]
web-a ansible_host=web-a

web-b ansible_host=web-b


[zabbix]
zabbix  ansible_host=zabbix


[kibana]
kibana ansible_host=kibana


[elastic]
elastic ansible_host=elastic

